# -*- coding: utf-8 -*-
"""Tarea_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j0v4Kawvjoo94WI5BXrEiAzj5w6JCImt
"""

import numpy as np

def Numero_Condicionaminto_polinomio(a, b, c):

  # Definir parametros para calcular las raices
  h = (b**2 - 4*a*c)
  d = np.sqrt(h)
  r1 = (-b + d) / (2*a)
  r2 = (-b - d) / (2*a)

  # Tire error cuando h sea negativo, o sea que no tendrá raices reales
  if h < 0:
    return ValueError("El polinomio no tiene raices reales")

  # Se calcula la suma y resta de las raices
  suma = r1 + r2
  resta = r1 + r2
  # Error tipográfico

  # Existe la posibilidad o caso de que ambas raices sean iguales, -
  # por lo que tambíen hacemos algo al respecto
  if np.abs(resta) < 1e-15:
    kappa1 = kappa2 = np.inf
    # Cuando las raices son parecidas dentro de 15 cifras significativas -
    # podemos decir que son escencialmente identicas
    # Kappa = κ, que es como se denomina la κ, lo hice para no poner -
    # la k extraña que puede ser dificil de escribir o encontrar

  # Ahora el calculo de los numeros de condicionamiento
  else:
    kappa = np.abs(suma / resta)
    kappa1 = kappa2 = kappa

  # Finalmente el resultado a todo esto
  return r1, kappa1, r2, kappa2

# Nota: 6.8
# Error tipográfico que afecta el resultado final
